---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to execute linux command directly 
    command: hostname -f
    register: myfirsttaskresult


  - name: i want to display first task result 
    debug:
        msg: "{{myfirsttaskresult}}"
