---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to crate a file  one
    file: 
       path: /home/maha/mytestONE
       state: touch
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy static index file into  node side
    copy:
       src:  myindex.html
       dest: /var/www/html/index.html
    notify: intallgit

  - name: copy dynamic index file into node side 
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restartwervers
  

  - name: download remote (internet) files 
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/maha/jenkins.war
      force_basic_auth: yes

  handlers:
  - name: restartwervers
    service:
      name: apache2
      state: restarted
  - name: intallgit
    apt:  
      name: git 
      state: present 

  


    
      