---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to crate a file  one
    file: 
       path: /home/maha/mytestONE
       state: touch
  - include_tasks: myfile.yml

  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: copy static index file into  node side
    copy:
       src:  myindex.html
       dest: /var/www/html/index.html

  - name: copy dynamic index file into node side 
    template:
        src: myindex.j2
        dest: /var/www/html/index.html



    
      